version: '3.8'

volumes:
  mysql_db: {}

services:
  phpmyadmin:
    image: phpmyadmin:5.2.1
    environment:
      - "PMA_HOST=mysql"
    ports:
      - "8081:80"

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=12345678"
    ports:
      - "3306:3306"

  httpd:
    build: .
    volumes:
      - ./htdocs:/var/www/html
    ports:
      - "8080:80"
